### PR TITLE
Add additional helper method: WithSequentialsId(), with a lambda to build derived Id properties

### PR DESCRIPTION
**Pull request by Brondahl**
This pattern was used a lot in Redburn, and feels like something that is generic enough and will be common enough (and is simple enough) to be worth including in the library

---
This change is [Reviewable](https://reviewable.io/reviews/softwire/lochnessbuilder/14)

### CODE REVIEW

**Review by benbelow — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/softwire/lochnessbuilder/14)* status: all files reviewed, 2 unresolved discussions (waiting on @Brondahl and @JonArtus)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/softwire/lochnessbuilder/14#-MsZcLnvAndoHX3w1Hw2):*
typo in the commit: should be `WithSequentialIds()` 
___
*[Tests/WithSequentialIds_Tests.cs, line 26 at r1](https://reviewable.io/reviews/softwire/lochnessbuilder/14#-MsZcEKoEUiuRXxgaZ8h:-MsZcEKp9mCbrkpLqLuD:b-5dm0vp) ([raw file](https://github.com/softwire/lochnessbuilder/blob/c47e1b1d10a4d824cecb4687fc8787db29e46ca4/Tests/WithSequentialIds_Tests.cs#L26)):*
> ```Smalltalk
>         }
> 
>         [Test,
> ```

is this `Test` necessary? I've never used a `Test` attribute as well as `TestCase` before...

**Comment by Brondahl** [comment]
___
*[Tests/WithSequentialIds_Tests.cs, line 26 at r1](https://reviewable.io/reviews/softwire/lochnessbuilder/14#-MsZcEKoEUiuRXxgaZ8h:-Ms_fYLq09HtMNq_tfLJ:b-spv3gw) ([raw file](https://github.com/softwire/lochnessbuilder/blob/c47e1b1d10a4d824cecb4687fc8787db29e46ca4/Tests/WithSequentialIds_Tests.cs#L26)):*
🤯
No, apparently not.
> TestCaseAttribute serves the dual purpose of marking a method with parameters as a test method and providing inline data to be used when invoking that method. (https://docs.nunit.org/2.5/testCase.html)
Will remove.

**Review by Brondahl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/softwire/lochnessbuilder/14)* status: all files reviewed, 1 unresolved discussion (waiting on @benbelow and @JonArtus)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/softwire/lochnessbuilder/14#-MsZcLnvAndoHX3w1Hw2):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

typo in the commit: should be `WithSequentialIds()` 
</blockquote></details>

Agreed, but won't fix, alas.

**Review by benbelow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/softwire/lochnessbuilder/14)* status: all files reviewed, 1 unresolved discussion (waiting on @Brondahl and @JonArtus)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/softwire/lochnessbuilder/14#-MsZcLnvAndoHX3w1Hw2):*
<details><summary><i>Previously, Brondahl (Michael McLean) wrote…</i></summary><blockquote>

Agreed, but won't fix, alas.
</blockquote></details>

if this isn't merged yet, is there a downside to amending + force-pushing?

I think there's a very mild argument in favour of correcting it, just in case anyone tries to track down the history of this feature
___
*[Tests/WithSequentialIds_Tests.cs, line 26 at r1](https://reviewable.io/reviews/softwire/lochnessbuilder/14#-MsZcEKoEUiuRXxgaZ8h:-Ms_iGcu829OQoGX7XWQ:b-8fx2u7) ([raw file](https://github.com/softwire/lochnessbuilder/blob/c47e1b1d10a4d824cecb4687fc8787db29e46ca4/Tests/WithSequentialIds_Tests.cs#L26)):*
<details><summary><i>Previously, Brondahl (Michael McLean) wrote…</i></summary><blockquote>

🤯
No, apparently not.
> TestCaseAttribute serves the dual purpose of marking a method with parameters as a test method and providing inline data to be used when invoking that method. (https://docs.nunit.org/2.5/testCase.html)
Will remove.
</blockquote></details>

:+1:

**Comment by Brondahl** [comment]
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/softwire/lochnessbuilder/14#-MsZcLnvAndoHX3w1Hw2):*
> if this isn't merged yet
Alas it is already merged, and indeed published.
This was prompted by heavy "use" in the Redburn codebase, so I made and published the change whilst doing the work
I've had too much of the LNB work stagnate for months and years :) and it was sufficiently trivial and self-testing that I felt it was an acceptable trade.
#cowboy

> I think there's a very mild argument in favour of correcting it, just in case anyone tries to track down the history of this feature
Agreed; and I'd 100% do so if it were on a branch. And on a project this small ... _maybe_ even on `master`. But not with a published nuget version tag, I think.

**Review by Brondahl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/softwire/lochnessbuilder/14)* status: all files reviewed, 1 unresolved discussion (waiting on @benbelow and @JonArtus)

___
*[Tests/WithSequentialIds_Tests.cs, line 26 at r1](https://reviewable.io/reviews/softwire/lochnessbuilder/14#-MsZcEKoEUiuRXxgaZ8h:-Ms_jmMUDc-CLfy16bhD:b-896fix) ([raw file](https://github.com/softwire/lochnessbuilder/blob/c47e1b1d10a4d824cecb4687fc8787db29e46ca4/Tests/WithSequentialIds_Tests.cs#L26)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Done.

**Review by benbelow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/softwire/lochnessbuilder/14)* status: all files reviewed, 1 unresolved discussion (waiting on @benbelow and @JonArtus)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/softwire/lochnessbuilder/14#-MsZcLnvAndoHX3w1Hw2):*
<details><summary><i>Previously, Brondahl (Michael McLean) wrote…</i></summary><blockquote>

> if this isn't merged yet
Alas it is already merged, and indeed published.
This was prompted by heavy "use" in the Redburn codebase, so I made and published the change whilst doing the work
I've had too much of the LNB work stagnate for months and years :) and it was sufficiently trivial and self-testing that I felt it was an acceptable trade.
#cowboy

> I think there's a very mild argument in favour of correcting it, just in case anyone tries to track down the history of this feature
Agreed; and I'd 100% do so if it were on a branch. And on a project this small ... _maybe_ even on `master`. But not with a published nuget version tag, I think.
</blockquote></details>

yup, fair enough! If this is post-merge/release, definitely not worth the hassle

**Pull request closed without merging**
